/*!
jQuery Waypoints - v2.0.5
Copyright (c) 2011-2014 Caleb Troughton
Licensed under the MIT license.
https://github.com/imakewebthings/jquery-waypoints/blob/master/licenses.txt
*/
(function(){var e=[].indexOf||function(t){for(var e=0,n=this.length;e<n;e++){if(e in this&&this[e]===t)return e};return-1},t=[].slice;(function(t,e){if(typeof define==='function'&&define.amd){return define('waypoints',['jquery'],function(n){return e(n,t)})}
else{return e(t.jQuery,t)}})(window,function(n,r){var h,w,d,s,g,u,f,p,i,o,y,v,m,a,c,l;h=n(r);p=e.call(r,'ontouchstart')>=0;s={horizontal:{},vertical:{}};g=1;f={};u='waypoints-context-id';y='resize.waypoints';v='scroll.waypoints';m=1;a='waypoints-waypoint-ids';c='waypoint';l='waypoints';w=function(){function t(t){var e=this;this.$element=t;this.element=t[0];this.didResize=!1;this.didScroll=!1;this.id='context'+g++;this.oldScroll={x:t.scrollLeft(),y:t.scrollTop()};this.waypoints={horizontal:{},vertical:{}};this.element[u]=this.id;f[this.id]=this;t.bind(v,function(){var t;if(!(e.didScroll||p)){e.didScroll=!0;t=function(){e.doScroll();return e.didScroll=!1};return r.setTimeout(t,n[l].settings.scrollThrottle)}});t.bind(y,function(){var t;if(!e.didResize){e.didResize=!0;t=function(){n[l]('refresh');return e.didResize=!1};return r.setTimeout(t,n[l].settings.resizeThrottle)}})};t.prototype.doScroll=function(){var t,e=this;t={horizontal:{newScroll:this.$element.scrollLeft(),oldScroll:this.oldScroll.x,forward:'right',backward:'left'},vertical:{newScroll:this.$element.scrollTop(),oldScroll:this.oldScroll.y,forward:'down',backward:'up'}};if(p&&(!t.vertical.oldScroll||!t.vertical.newScroll)){n[l]('refresh')};n.each(t,function(t,r){var l,o,i;i=[];o=r.newScroll>r.oldScroll;l=o?r.forward:r.backward;n.each(e.waypoints[t],function(t,e){var n,o;if(r.oldScroll<(n=e.offset)&&n<=r.newScroll){return i.push(e)}
else if(r.newScroll<(o=e.offset)&&o<=r.oldScroll){return i.push(e)}});i.sort(function(t,e){return t.offset-e.offset});if(!o){i.reverse()};return n.each(i,function(t,e){if(e.options.continuous||t===i.length-1){return e.trigger([l])}})});return this.oldScroll={x:t.horizontal.newScroll,y:t.vertical.newScroll}};t.prototype.refresh=function(){var r,e,t,i=this;t=n.isWindow(this.element);e=this.$element.offset();this.doScroll();r={horizontal:{contextOffset:t?0:e.left,contextScroll:t?0:this.oldScroll.x,contextDimension:this.$element.width(),oldScroll:this.oldScroll.x,forward:'right',backward:'left',offsetProp:'left'},vertical:{contextOffset:t?0:e.top,contextScroll:t?0:this.oldScroll.y,contextDimension:t?n[l]('viewportHeight'):this.$element.height(),oldScroll:this.oldScroll.y,forward:'down',backward:'up',offsetProp:'top'}};return n.each(r,function(t,e){return n.each(i.waypoints[t],function(t,r){var i,l,o,s,f;i=r.options.offset;o=r.offset;l=n.isWindow(r.element)?0:r.$element.offset()[e.offsetProp];if(n.isFunction(i)){i=i.apply(r.element)}
else if(typeof i==='string'){i=parseFloat(i);if(r.options.offset.indexOf('%')>-1){i=Math.ceil(e.contextDimension*i/100)}};r.offset=l-e.contextOffset+e.contextScroll-i;if(r.options.onlyOnScroll&&o!=null||!r.enabled){return};if(o!==null&&o<(s=e.oldScroll)&&s<=r.offset){return r.trigger([e.backward])}
else if(o!==null&&o>(f=e.oldScroll)&&f>=r.offset){return r.trigger([e.forward])}
else if(o===null&&e.oldScroll>=r.offset){return r.trigger([e.forward])}})})};t.prototype.checkEmpty=function(){if(n.isEmptyObject(this.waypoints.horizontal)&&n.isEmptyObject(this.waypoints.vertical)){this.$element.unbind([y,v].join(' '));return delete f[this.id]}};return t}();d=function(){function t(t,e,r){var i,o;if(r.offset==='bottom-in-view'){r.offset=function(){var t;t=n[l]('viewportHeight');if(!n.isWindow(e.element)){t=e.$element.height()};return t-n(this).outerHeight()}};this.$element=t;this.element=t[0];this.axis=r.horizontal?'horizontal':'vertical';this.callback=r.handler;this.context=e;this.enabled=r.enabled;this.id='waypoints'+m++;this.offset=null;this.options=r;e.waypoints[this.axis][this.id]=this;s[this.axis][this.id]=this;i=(o=this.element[a])!=null?o:[];i.push(this.id);this.element[a]=i};t.prototype.trigger=function(t){if(!this.enabled){return};if(this.callback!=null){this.callback.apply(this.element,t)};if(this.options.triggerOnce){return this.destroy()}};t.prototype.disable=function(){return this.enabled=!1};t.prototype.enable=function(){this.context.refresh();return this.enabled=!0};t.prototype.destroy=function(){delete s[this.axis][this.id];delete this.context.waypoints[this.axis][this.id];return this.context.checkEmpty()};t.getWaypointsByElement=function(t){var r,e;e=t[a];if(!e){return[]};r=n.extend({},s.horizontal,s.vertical);return n.map(e,function(t){return r[t]})};return t}();o={init:function(t,e){var r;e=n.extend({},n.fn[c].defaults,e);if((r=e.handler)==null){e.handler=t};this.each(function(){var i,r,t,o;i=n(this);t=(o=e.context)!=null?o:n.fn[c].defaults.context;if(!n.isWindow(t)){t=i.closest(t)};t=n(t);r=f[t[0][u]];if(!r){r=new w(t)};return new d(i,r,e)});n[l]('refresh');return this},disable:function(){return o._invoke.call(this,'disable')},enable:function(){return o._invoke.call(this,'enable')},destroy:function(){return o._invoke.call(this,'destroy')},prev:function(t,e){return o._traverse.call(this,t,e,function(t,e,n){if(e>0){return t.push(n[e-1])}})},next:function(t,e){return o._traverse.call(this,t,e,function(t,e,n){if(e<n.length-1){return t.push(n[e+1])}})},_traverse:function(t,e,o){var l,s;if(t==null){t='vertical'};if(e==null){e=r};s=i.aggregate(e);l=[];this.each(function(){var e;e=n.inArray(this,s[t]);return o(l,e,s[t])});return this.pushStack(l)},_invoke:function(t){this.each(function(){var e;e=d.getWaypointsByElement(this);return n.each(e,function(e,n){n[t]();return!0})});return this}};n.fn[c]=function(){var r,e;e=arguments[0],r=2<=arguments.length?t.call(arguments,1):[];if(o[e]){return o[e].apply(this,r)}
else if(n.isFunction(e)){return o.init.apply(this,arguments)}
else if(n.isPlainObject(e)){return o.init.apply(this,[null,e])}
else if(!e){return n.error('jQuery Waypoints needs a callback function or handler option.')}
else{return n.error('The '+e+' method does not exist in jQuery Waypoints.')}};n.fn[c].defaults={context:r,continuous:!0,enabled:!0,horizontal:!1,offset:0,triggerOnce:!1};i={refresh:function(){return n.each(f,function(t,e){return e.refresh()})},viewportHeight:function(){var t;return(t=r.innerHeight)!=null?t:h.height()},aggregate:function(t){var r,e,i;r=s;if(t){r=(i=f[n(t)[0][u]])!=null?i.waypoints:void 0};if(!r){return[]};e={horizontal:[],vertical:[]};n.each(e,function(t,i){n.each(r[t],function(t,e){return i.push(e)});i.sort(function(t,e){return t.offset-e.offset});e[t]=n.map(i,function(t){return t.element});return e[t]=n.unique(e[t])});return e},above:function(t){if(t==null){t=r};return i._filter(t,'vertical',function(t,e){return e.offset<=t.oldScroll.y})},below:function(t){if(t==null){t=r};return i._filter(t,'vertical',function(t,e){return e.offset>t.oldScroll.y})},left:function(t){if(t==null){t=r};return i._filter(t,'horizontal',function(t,e){return e.offset<=t.oldScroll.x})},right:function(t){if(t==null){t=r};return i._filter(t,'horizontal',function(t,e){return e.offset>t.oldScroll.x})},enable:function(){return i._invoke('enable')},disable:function(){return i._invoke('disable')},destroy:function(){return i._invoke('destroy')},extendFn:function(t,e){return o[t]=e},_invoke:function(t){var e;e=n.extend({},s.vertical,s.horizontal);return n.each(e,function(e,n){n[t]();return!0})},_filter:function(t,e,r){var i,o;i=f[n(t)[0][u]];if(!i){return[]};o=[];n.each(i.waypoints[e],function(t,e){if(r(i,e)){return o.push(e)}});o.sort(function(t,e){return t.offset-e.offset});return n.map(o,function(t){return t.element})}};n[l]=function(){var n,e;e=arguments[0],n=2<=arguments.length?t.call(arguments,1):[];if(i[e]){return i[e].apply(null,n)}
else{return i.aggregate.call(null,e)}};n[l].settings={resizeThrottle:100,scrollThrottle:30};return h.on('load.waypoints',function(){return n[l]('refresh')})})}).call(this);